runtime: php55
api_version: 1
service: front-end
threadsafe: true

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /static
    static_dir: build/static
  - url: /[^/]\.[^/]*$
    static_dir: build
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
