runtime: nodejs10
service: front-end

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /static
    static_dir: build/static
  - url: /favicon\.ico$
    static_files: build/favicon.ico
    upload: build/favicon.ico
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
